screen:
  width: 500
  height: 500
  z: 1.25

camera:
  position: [0, 0, 2.25]

reflection_depth: 3

lights:
  - position: [-4, 10, 3]
    color: {ambient: [1, 1, 1], diffuse: [1, 1, 1], specular: [1, 1, 1]}
    intensity: 1.0
  - position: [4, 2, 3]
    color: {ambient: [1, 1, 1], diffuse: [1, 1, 1], specular: [1, 1, 1]}
    intensity: 1.0

objects:
  - type: Sphere
    position: [-0.5, 0.1, 0.5]
    radius: 0.17
    color: {ambient: [0.07, 0, 0.1], diffuse: [0.7, 0, 1], specular: [1, 1, 1]}
    material: {luster: 100, reflectivity: 0.75}

  - type: Sphere
    position: [0, 0.01, -1]
    radius: 0.75
    color: {ambient: [0, 1, 1], diffuse: [0, 0.1, 0.1], specular: [1, 1, 1]}
    material: {luster: 100, reflectivity: 0.75}

  - type: Sphere
    position: [0.3, 0.01, 0.35]
    radius: 0.2
    color: {ambient: [0, 0.1, 0], diffuse: [0, 0.7, 0], specular: [1, 1, 1]}
    material: {luster: 100, reflectivity: 0.75}

  - type: Plane
    position: [0, 1, 0]
    distance: -1
    color: {ambient: [0.1, 0.1, 0.1], diffuse: [0.5, 0.5, 0.5], specular: [1, 1, 1]}
    material: {luster: 50, reflectivity: 0.2}
    pattern:
      type: checkerboard
      scale: 3

  - type: Plane
    position: [1, 3, 2]
    distance: -10
    color: {ambient: [1, 0.4, 0.28], diffuse: [1, 0.04, 0.028], specular: [1, 1, 1]}
    material: {luster: 50, reflectivity: 0.2}
